/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HealthLiveRouteImport } from './routes/health.live'
import { Route as HealthReadyRouteImport } from './routes/health.ready'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiImagesIndexRouteImport } from './routes/api/images/index'
import { Route as ApiImagesIdRouteImport } from './routes/api/images/$id'
import { Route as ApiImagesIdCompleteRouteImport } from './routes/api/images/$id.complete'
import { Route as ApiImagesIdDownloadRouteImport } from './routes/api/images/$id.download'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthLiveRoute = HealthLiveRouteImport.update({
  id: '/health/live',
  path: '/health/live',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthReadyRoute = HealthReadyRouteImport.update({
  id: '/health/ready',
  path: '/health/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImagesIndexRoute = ApiImagesIndexRouteImport.update({
  id: '/api/images/',
  path: '/api/images/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImagesIdRoute = ApiImagesIdRouteImport.update({
  id: '/api/images/$id',
  path: '/api/images/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImagesIdCompleteRoute = ApiImagesIdCompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => ApiImagesIdRoute,
} as any)
const ApiImagesIdDownloadRoute = ApiImagesIdDownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => ApiImagesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/health/live': typeof HealthLiveRoute
  '/health/ready': typeof HealthReadyRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/images/$id': typeof ApiImagesIdRouteWithChildren
  '/api/images/': typeof ApiImagesIndexRoute
  '/api/images/$id/complete': typeof ApiImagesIdCompleteRoute
  '/api/images/$id/download': typeof ApiImagesIdDownloadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health/live': typeof HealthLiveRoute
  '/health/ready': typeof HealthReadyRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/images/$id': typeof ApiImagesIdRouteWithChildren
  '/api/images': typeof ApiImagesIndexRoute
  '/api/images/$id/complete': typeof ApiImagesIdCompleteRoute
  '/api/images/$id/download': typeof ApiImagesIdDownloadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/health/live': typeof HealthLiveRoute
  '/health/ready': typeof HealthReadyRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/images/$id': typeof ApiImagesIdRouteWithChildren
  '/api/images/': typeof ApiImagesIndexRoute
  '/api/images/$id/complete': typeof ApiImagesIdCompleteRoute
  '/api/images/$id/download': typeof ApiImagesIdDownloadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health/live'
    | '/health/ready'
    | '/api/auth/$'
    | '/api/images/$id'
    | '/api/images/'
    | '/api/images/$id/complete'
    | '/api/images/$id/download'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health/live'
    | '/health/ready'
    | '/api/auth/$'
    | '/api/images/$id'
    | '/api/images'
    | '/api/images/$id/complete'
    | '/api/images/$id/download'
  id:
    | '__root__'
    | '/'
    | '/health/live'
    | '/health/ready'
    | '/api/auth/$'
    | '/api/images/$id'
    | '/api/images/'
    | '/api/images/$id/complete'
    | '/api/images/$id/download'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HealthLiveRoute: typeof HealthLiveRoute
  HealthReadyRoute: typeof HealthReadyRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiImagesIdRoute: typeof ApiImagesIdRouteWithChildren
  ApiImagesIndexRoute: typeof ApiImagesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health/live': {
      id: '/health/live'
      path: '/health/live'
      fullPath: '/health/live'
      preLoaderRoute: typeof HealthLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health/ready': {
      id: '/health/ready'
      path: '/health/ready'
      fullPath: '/health/ready'
      preLoaderRoute: typeof HealthReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/images/': {
      id: '/api/images/'
      path: '/api/images'
      fullPath: '/api/images/'
      preLoaderRoute: typeof ApiImagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/images/$id': {
      id: '/api/images/$id'
      path: '/api/images/$id'
      fullPath: '/api/images/$id'
      preLoaderRoute: typeof ApiImagesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/images/$id/complete': {
      id: '/api/images/$id/complete'
      path: '/complete'
      fullPath: '/api/images/$id/complete'
      preLoaderRoute: typeof ApiImagesIdCompleteRouteImport
      parentRoute: typeof ApiImagesIdRoute
    }
    '/api/images/$id/download': {
      id: '/api/images/$id/download'
      path: '/download'
      fullPath: '/api/images/$id/download'
      preLoaderRoute: typeof ApiImagesIdDownloadRouteImport
      parentRoute: typeof ApiImagesIdRoute
    }
  }
}

interface ApiImagesIdRouteChildren {
  ApiImagesIdCompleteRoute: typeof ApiImagesIdCompleteRoute
  ApiImagesIdDownloadRoute: typeof ApiImagesIdDownloadRoute
}

const ApiImagesIdRouteChildren: ApiImagesIdRouteChildren = {
  ApiImagesIdCompleteRoute: ApiImagesIdCompleteRoute,
  ApiImagesIdDownloadRoute: ApiImagesIdDownloadRoute,
}

const ApiImagesIdRouteWithChildren = ApiImagesIdRoute._addFileChildren(
  ApiImagesIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HealthLiveRoute: HealthLiveRoute,
  HealthReadyRoute: HealthReadyRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiImagesIdRoute: ApiImagesIdRouteWithChildren,
  ApiImagesIndexRoute: ApiImagesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
